{{ config(materialized='table', alias='first_model', tags=["nightly", "example"] ) }}

execute immediate
$$
declare
rs resultset;
query varchar default 'SELECT '
|| (select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'CUSTOMERSOURCEKEY' AND D_2_I_ENTITY_NAME = 'Customer') || ' AS CUSTOMERID, '
|| (select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'CUSTOMERSOURCEKEY' AND D_2_I_ENTITY_NAME = 'Customer') || ' AS CUSTOMERSOURCEKEY, '
|| (select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'FIRSTNAME' AND D_2_I_ENTITY_NAME = 'Customer') || '||\', \' ||'
|| (select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'LASTNAME' AND D_2_I_ENTITY_NAME = 'Customer') || ' AS CUSTOMERNAME,'
|| (select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'AGE' AND D_2_I_ENTITY_NAME = 'Customer') || ' AS AGE,'
|| (select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'GENDER' AND D_2_I_ENTITY_NAME = 'Customer') || ' AS GENDER,'
|| (select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'EMAIL' AND D_2_I_ENTITY_NAME = 'Customer') || ' AS EMAIL,'
|| (select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'ADDRESS' AND D_2_I_ENTITY_NAME = 'Customer') || ' AS ADDRESS,'
|| 'CASE WHEN '||(select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'ISACTIVE' AND D_2_I_ENTITY_NAME = 'Customer') || ' IS NULL THEN 1 ELSE ' || (select CUSTOMER_ATTRIBUTE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'ISACTIVE' AND D_2_I_ENTITY_NAME = 'Customer') || ' END AS ISACTIVE'

||
' FROM
DATA_TO_INSIGHTS.RDS_RAW_DATA_DBO.'||(select CUSTOMER_ENTITY_TABLE_NAME from "DATA_TO_INSIGHTS"."HM_AWS_S3"."MAPPING_TEMPLATE" WHERE D_2_I_ATTRIBUTE_NAME = 'CUSTOMERSOURCEKEY' AND D_2_I_ENTITY_NAME = 'Customer');
begin
--return query;
rs := (execute immediate :query );
return table(rs);



end;
$$;


